name: 'ctest build'
description: 'GitHub Action that make CI builds using ctest'
author: 'Stephan Gatzka <@gatzka>'
inputs: 
  install_deps:
    description: 'User defined script to install build dependencies in ubuntu'
    required: false 
  ctest_toolchain_file:
    description: 'User defined toolchain file to build project'
    required: false 
  ctest_configuration_type:
    description: 'ctest configuration type like Debug|Release'
    required: false 
  ctest_binary_directory:
    description: 'ctest build directory'
    required: false 
  ctest_analyzer:
    description: 'ctest analyzer like clang-tidy or scan-build'
    required: false 
  ctest_run_tests:
    description: 'Enable/disable running ctest test step'
    required: false 
  ssh_key:
    description: 'ssh key used for FetchContent'
    required: false 
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.install_deps}}
    - ${{ inputs.ctest_toolchain_file}}
    - ${{ inputs.ctest_configuration_type}}
    - ${{ inputs.ctest_binary_directory}}
    - ${{ inputs.ctest_analyzer}}
    - ${{ inputs.ctest_run_tests}}
    - ${{ inputs.ssh_key}}

